from java
maintainer rhythmbhiwani@gmail.com
env classname=JavaCode
run mkdir /codes
add JavaCode.java /codes/JavaCode.java
#now compiling java code
workdir /codes/
run javac JavaCode.java
CMD java JavaCode