FROM nginx
#using ngnix web server from Dockerhub
MAINTAINER rhythmbhiwani@gmail.com
COPY website /usr/share/nginx/html/
# copy will only copy all the content of website not the folder
# location folder
# /usr/share/nginx/html/ document root for Ngnix webserver
EXPOSE 80
#this will be port of ngnix webserver